---
  title: "1_pcangsd.Rmd"
author: "Andrea Estandia<br>"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  toc: true
toc_depth: 4
editor_options:
  chunk_output_type: console
---
  <br>
  
```{r setup, echo=FALSE}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r, echo=FALSE}
source("./src/phylo_silvereye_source.R")
```

Load pop information
```{r}
sex <-
  read_csv(file.path(data_path,"dfs", "geneticsex.csv"))

sample <-  read_csv(file.path(reports_path,
                              "pcangsd",
                              "sm",
                              "id_sm.csv"))

label <- 
  read_csv(file.path(data_path,"dfs", "list_samples_phylogeny.csv")) %>% 
  left_join(sex) %>% 
  filter(id %in% sample$id)
```

Load covariance matrix
```{r}
cov_mat <- 
  as.matrix(read.table(file.path(reports_path, 
                                 "pcangsd", 
                                 "sm",
                                 "pca_sm.tree.cov"), header=F))
```

Compute eigenvalues and MDS
```{r}
mds.cor <- (1 - cov_mat) %>%
  cmdscale(k=3, eig = TRUE)

colnames(mds.cor$points) <- c("Dim.1", "Dim.2", "Dim.3")
rownames(mds.cor$points) <-
  label$pop

#Percentage of the variance explained by each dimension
df_var_mds <- 
  as.data.frame(round(mds.cor$eig*100/sum(mds.cor$eig),1)/100)

rownames(df_var_mds) <- 
  paste0("Dim.", seq(1:dim(df_var_mds)[1]))
df_var_mds$PC <- rownames(df_var_mds)
colnames(df_var_mds) <- c("variance_explained", "Dim")

#Do PCA on cov matrix
pca <-
  eigen(cov_mat)

pca.mat <-
  as.matrix(pca$vectors %*% (diag(pca$values))^0.5)

nPC <-
  dim(pca$vectors)[2]

col_PC <- 
  vector(length=nPC)

for (i in 1 : nPC) {col_PC[i] <-
  paste0("PC",i)}

#add column names
colnames(pca.mat) <-
  c(col_PC)

#add row names
rownames(pca.mat) <-
  label$pop

#Calculate variance explained by each of the first four components

df_var_pca <- 
  as.data.frame(round(pca$values*100/sum(pca$values),1)/100) 


rownames(df_var_pca) <- 
  paste0("PC", seq(1:dim(df_var_pca)[1]))
df_var_pca$PC <- rownames(df_var_pca)
colnames(df_var_pca) <- c("variance_explained", "PC")
```

Calculate Kmeans
```{r}
kmeans_res<-
  kmeans(as.matrix(mds.cor$points[,1]), 
         c(min(mds.cor$points[,1]), 
           median(mds.cor$points[,1]), 
           max(mds.cor$points[,1])))
k_ss<-
  round(kmeans_res$betweenss/kmeans_res$totss,3)

k <- as.data.frame(kmeans_res$cluster)
colnames(k) <- "k"
```

Organise and create dataframe with MDS and PCA
```{r}
pca.mat <- 
  as.data.frame(pca.mat)

pca.mat$pop <- 
  label$pop

pca.mat$sample_name <- 
  label$sample_name

pca.out <- 
  pca.mat[,c(1:4)]

clusters <- 
  cbind(label, pca.out) %>%
  #select(-V3, -V4) %>% 
  cbind(mds.cor$points) %>% 
  cbind(k)
```

Plot variance explained
```{r}
df_var_mds$Dim <- factor(df_var_mds$Dim, levels = df_var_mds$Dim)

plot_mds <-
  df_var_mds %>% 
  slice(1, 2:10) %>% 
  ggplot(aes(x=as.factor(Dim), y=variance_explained))+
  geom_bar(stat='identity')+
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(size=text_size),
    axis.text.y = element_text(size = text_size),
    axis.title = element_text(size = text_size))+
  labs(x="\nDim", y="Variance explained\n", title="MDS",
       subtitle="Variance explained by each Dim\n")

df_var_pca$PC <- factor(df_var_pca$PC, levels = df_var_pca$PC)

plot_pca <-
  df_var_pca %>% 
  slice(1, 2:10) %>% 
  ggplot(aes(x=as.factor(PC), y=variance_explained))+
  geom_bar(stat='identity')+
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(size=text_size),
    axis.text.y = element_text(size = text_size),
    axis.title = element_text(size = text_size))+
  labs(x="\nPCA", y="Variance explained\n", title="PCA",
       subtitle="Variance explained by each PC\n")

plot_mds/plot_pca
```

Plot PC1 vs PC2
```{r}
plot_mds <-
  clusters %>%
  ggplot(aes(x = Dim.1, 
             y = Dim.2, 
             col = pop)) +
  geom_point() +
  # scale_color_manual(values = c(
  #   "#6a994e",
  #   "#219ebc",
  #   "#ff595e",
  #   "#d62828",
  #   "#ffb703",
  #   "#fb8b24"
  # )) +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(size = text_size),
    axis.text.y = element_text(size = text_size),
    axis.title = element_text(size = text_size),
    axis.ticks.x.bottom = element_blank(),
    axis.ticks.y.left = element_blank()
  ) +
  labs(x = "\nDim.1 (43.9%)",
       y = "Dim.2 (10.1%)\n",
       title = "MDS based on whole-genome data")

plot_pca_sm <-
  clusters %>%
  ggplot(aes(x = PC1,
             y = PC2,
             col = pop)) +
  geom_point() +
  # scale_color_manual(values = c(
  #   "#6a994e",
  #   "#219ebc",
  #   "#ff595e",
  #   "#d62828",
  #   "#ffb703",
  #   "#fb8b24"
  # )) +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(size = text_size),
    axis.text.y = element_text(size = text_size),
    axis.title = element_text(size = text_size),
    axis.ticks.x.bottom = element_blank(),
    axis.ticks.y.left = element_blank()
  ) +
  labs(x = "\nPC1 (53.1%)",
       y = "PC2 (24.7%)\n",
       title = "Southern Melanesia")+
  guides(color=guide_legend(title="Region"))

plot_pca_sm
plot_mds/plot_pca
```
